name: Test setup-rclone/service-account-file
on:
  push:
    paths:
      - service-account-file/action.yaml
      - .github/workflows/test-service-account-file.yaml
      
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [latest, "${{ vars.SPECIFIED_VERSION }}"]
        
    steps:
      - name: Setup Rclone using setup-rclone
        uses: AnimMouse/setup-rclone@main
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG_SERVICE_ACCOUNT_FILE_TEST }}
          version: ${{ matrix.version }}
          
      - name: Add Rclone service account file using setup-rclone/service-account-file
        uses: AnimMouse/setup-rclone/service-account-file@main
        with:
          service_account_filename: setup-rclone-test.json
          service_account_file: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_FILE }}
          
      - name: Test Rclone by listing remotes
        run: rclone listremotes
        
      - name: Test Rclone by listing test remote
        run: 'rclone lsd setup-rclone-test:'