name: Test setup-rclone/update-config
on:
  push:
    paths:
      - update-config/action.yaml
      - .github/workflows/test-update-config.yaml
  schedule:
    - cron: '7 11 1 * *'
  workflow_dispatch:
  
jobs:
  test-unix-like:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
      - name: Get past secret value
        run: echo $rclone_config | base64 -d
        env:
          rclone_config: ${{ matrix.os == 'macos-latest' && secrets.RCLONE_CONFIG_UPDATE_TEST_MACOS || secrets.RCLONE_CONFIG_UPDATE_TEST_UBUNTU }}
          
      - name: Get new secret value
        run: |
          mkdir ~/.config/rclone
          rclone_config=${{ github.run_id }}
          echo $rclone_config | tee ~/.config/rclone/rclone.conf
          
      - name: Update Rclone config using setup-rclone/update-config
        uses: AnimMouse/setup-rclone/update-config@main
        with:
          rclone_config_secret_name: ${{ matrix.os == 'macos-latest' && 'RCLONE_CONFIG_UPDATE_TEST_MACOS' || 'RCLONE_CONFIG_UPDATE_TEST_UBUNTU' }}
          token: ${{ secrets.GH_PAT }}
          
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Get past secret value
        run: '[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($env:rclone_config))'
        env:
          rclone_config: ${{ secrets.RCLONE_CONFIG_UPDATE_TEST_WINDOWS }}
          
      - name: Get new secret value
        run: |
          New-Item $env:APPDATA\rclone -ItemType Directory
          $rclone_config = "${{ github.run_id }}"
          $rclone_config
          [IO.File]::WriteAllBytes("$env:APPDATA\rclone\rclone.conf", [Text.Encoding]::UTF8.GetBytes($rclone_config))
          
      - name: Update Rclone config using setup-rclone/update-config
        uses: AnimMouse/setup-rclone/update-config@main
        with:
          rclone_config_secret_name: RCLONE_CONFIG_UPDATE_TEST_WINDOWS
          token: ${{ secrets.GH_PAT }}